"""Create counties table

Revision ID: 9385000d78f5
Revises:
Create Date: 2025-11-22 11:34:35.568735

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9385000d78f5"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "counties",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("value", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("counties")
    # ### end Alembic commands ###
